package com.eli.oneos.model.user;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_INFO.
 */
public class UserInfo {

    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String pwd;
    private Long time;
    private Integer uid;
    private Integer gid;
    private Integer admin;

    public UserInfo() {
    }

    public UserInfo(String name) {
        this.name = name;
    }

    public UserInfo(String name, String pwd, Long time, Integer uid, Integer gid, Integer admin) {
        this.name = name;
        this.pwd = pwd;
        this.time = time;
        this.uid = uid;
        this.gid = gid;
        this.admin = admin;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPwd() {
        return pwd;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getUid() {
        return uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public Integer getGid() {
        return gid;
    }

    public void setGid(Integer gid) {
        this.gid = gid;
    }

    public Integer getAdmin() {
        return admin;
    }

    public void setAdmin(Integer admin) {
        this.admin = admin;
    }

}
