package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BACKUP_INFO_HISTORY.
 */
public class BackupInfoHistory {

    private Long id;
    private Long uid;
    private String type;
    private Long time;
    private Long count;

    public BackupInfoHistory() {
    }

    public BackupInfoHistory(Long id) {
        this.id = id;
    }

    public BackupInfoHistory(Long id, Long uid, String type, Long time, Long count) {
        this.id = id;
        this.uid = uid;
        this.type = type;
        this.time = time;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

}
