package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BACKUP_INFO.
 */
public class BackupInfo {

    private Long id;
    /** Not-null value. */
    private String mac;
    /** Not-null value. */
    private String user;
    /** Not-null value. */
    private String path;
    private Long time;
    private Long count;
    private Integer priority;
    private String type;

    public BackupInfo() {
    }

    public BackupInfo(Long id) {
        this.id = id;
    }

    public BackupInfo(Long id, String mac, String user, String path, Long time, Long count, Integer priority, String type) {
        this.id = id;
        this.mac = mac;
        this.user = user;
        this.path = path;
        this.time = time;
        this.count = count;
        this.priority = priority;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMac() {
        return mac;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /** Not-null value. */
    public String getUser() {
        return user;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser(String user) {
        this.user = user;
    }

    /** Not-null value. */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(String path) {
        this.path = path;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public Integer getPriority() {
        return priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
