package com.eli.oneos.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.eli.oneos.db.greendao.BackupFileInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BACKUP_FILE_INFO.
*/
public class BackupFileInfoDao extends AbstractDao<BackupFileInfo, Long> {

    public static final String TABLENAME = "BACKUP_FILE_INFO";

    /**
     * Properties of entity BackupFileInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Mac = new Property(1, String.class, "mac", false, "MAC");
        public final static Property User = new Property(2, String.class, "user", false, "USER");
        public final static Property Path = new Property(3, String.class, "path", false, "PATH");
        public final static Property Time = new Property(4, Long.class, "time", false, "TIME");
        public final static Property Count = new Property(5, Long.class, "count", false, "COUNT");
        public final static Property Priority = new Property(6, Integer.class, "priority", false, "PRIORITY");
        public final static Property Type = new Property(7, String.class, "type", false, "TYPE");
    };


    public BackupFileInfoDao(DaoConfig config) {
        super(config);
    }
    
    public BackupFileInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BACKUP_FILE_INFO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'MAC' TEXT NOT NULL ," + // 1: mac
                "'USER' TEXT NOT NULL ," + // 2: user
                "'PATH' TEXT NOT NULL ," + // 3: path
                "'TIME' INTEGER," + // 4: time
                "'COUNT' INTEGER," + // 5: count
                "'PRIORITY' INTEGER," + // 6: priority
                "'TYPE' TEXT);"); // 7: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BACKUP_FILE_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BackupFileInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMac());
        stmt.bindString(3, entity.getUser());
        stmt.bindString(4, entity.getPath());
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(5, time);
        }
 
        Long count = entity.getCount();
        if (count != null) {
            stmt.bindLong(6, count);
        }
 
        Integer priority = entity.getPriority();
        if (priority != null) {
            stmt.bindLong(7, priority);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(8, type);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BackupFileInfo readEntity(Cursor cursor, int offset) {
        BackupFileInfo entity = new BackupFileInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // mac
            cursor.getString(offset + 2), // user
            cursor.getString(offset + 3), // path
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // time
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // count
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // priority
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BackupFileInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMac(cursor.getString(offset + 1));
        entity.setUser(cursor.getString(offset + 2));
        entity.setPath(cursor.getString(offset + 3));
        entity.setTime(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setCount(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setPriority(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setType(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BackupFileInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BackupFileInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
