package com.eli.oneos.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.eli.oneos.db.greendao.DeviceInfo;
import com.eli.oneos.db.greendao.UserInfo;
import com.eli.oneos.db.greendao.UserSettings;
import com.eli.oneos.db.greendao.BackupFile;
import com.eli.oneos.db.greendao.BackupInfo;

import com.eli.oneos.db.greendao.DeviceInfoDao;
import com.eli.oneos.db.greendao.UserInfoDao;
import com.eli.oneos.db.greendao.UserSettingsDao;
import com.eli.oneos.db.greendao.BackupFileDao;
import com.eli.oneos.db.greendao.BackupInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig userSettingsDaoConfig;
    private final DaoConfig backupFileDaoConfig;
    private final DaoConfig backupInfoDaoConfig;

    private final DeviceInfoDao deviceInfoDao;
    private final UserInfoDao userInfoDao;
    private final UserSettingsDao userSettingsDao;
    private final BackupFileDao backupFileDao;
    private final BackupInfoDao backupInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceInfoDaoConfig = daoConfigMap.get(DeviceInfoDao.class).clone();
        deviceInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        userSettingsDaoConfig = daoConfigMap.get(UserSettingsDao.class).clone();
        userSettingsDaoConfig.initIdentityScope(type);

        backupFileDaoConfig = daoConfigMap.get(BackupFileDao.class).clone();
        backupFileDaoConfig.initIdentityScope(type);

        backupInfoDaoConfig = daoConfigMap.get(BackupInfoDao.class).clone();
        backupInfoDaoConfig.initIdentityScope(type);

        deviceInfoDao = new DeviceInfoDao(deviceInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        userSettingsDao = new UserSettingsDao(userSettingsDaoConfig, this);
        backupFileDao = new BackupFileDao(backupFileDaoConfig, this);
        backupInfoDao = new BackupInfoDao(backupInfoDaoConfig, this);

        registerDao(DeviceInfo.class, deviceInfoDao);
        registerDao(UserInfo.class, userInfoDao);
        registerDao(UserSettings.class, userSettingsDao);
        registerDao(BackupFile.class, backupFileDao);
        registerDao(BackupInfo.class, backupInfoDao);
    }
    
    public void clear() {
        deviceInfoDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
        userSettingsDaoConfig.getIdentityScope().clear();
        backupFileDaoConfig.getIdentityScope().clear();
        backupInfoDaoConfig.getIdentityScope().clear();
    }

    public DeviceInfoDao getDeviceInfoDao() {
        return deviceInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public UserSettingsDao getUserSettingsDao() {
        return userSettingsDao;
    }

    public BackupFileDao getBackupFileDao() {
        return backupFileDao;
    }

    public BackupInfoDao getBackupInfoDao() {
        return backupInfoDao;
    }

}
