package com.eli.oneos.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.eli.oneos.db.greendao.UserInfo;
import com.eli.oneos.db.greendao.DeviceHistory;

import com.eli.oneos.db.greendao.UserInfoDao;
import com.eli.oneos.db.greendao.DeviceHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig deviceHistoryDaoConfig;

    private final UserInfoDao userInfoDao;
    private final DeviceHistoryDao deviceHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        deviceHistoryDaoConfig = daoConfigMap.get(DeviceHistoryDao.class).clone();
        deviceHistoryDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        deviceHistoryDao = new DeviceHistoryDao(deviceHistoryDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(DeviceHistory.class, deviceHistoryDao);
    }
    
    public void clear() {
        userInfoDaoConfig.getIdentityScope().clear();
        deviceHistoryDaoConfig.getIdentityScope().clear();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public DeviceHistoryDao getDeviceHistoryDao() {
        return deviceHistoryDao;
    }

}
