package com.eli.oneos.db.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.eli.oneos.db.greendao.UserHistory;
import com.eli.oneos.db.greendao.DeviceHistory;

import com.eli.oneos.db.greendao.UserHistoryDao;
import com.eli.oneos.db.greendao.DeviceHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userHistoryDaoConfig;
    private final DaoConfig deviceHistoryDaoConfig;

    private final UserHistoryDao userHistoryDao;
    private final DeviceHistoryDao deviceHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userHistoryDaoConfig = daoConfigMap.get(UserHistoryDao.class).clone();
        userHistoryDaoConfig.initIdentityScope(type);

        deviceHistoryDaoConfig = daoConfigMap.get(DeviceHistoryDao.class).clone();
        deviceHistoryDaoConfig.initIdentityScope(type);

        userHistoryDao = new UserHistoryDao(userHistoryDaoConfig, this);
        deviceHistoryDao = new DeviceHistoryDao(deviceHistoryDaoConfig, this);

        registerDao(UserHistory.class, userHistoryDao);
        registerDao(DeviceHistory.class, deviceHistoryDao);
    }
    
    public void clear() {
        userHistoryDaoConfig.getIdentityScope().clear();
        deviceHistoryDaoConfig.getIdentityScope().clear();
    }

    public UserHistoryDao getUserHistoryDao() {
        return userHistoryDao;
    }

    public DeviceHistoryDao getDeviceHistoryDao() {
        return deviceHistoryDao;
    }

}
