package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEVICE_INFO.
 */
public class DeviceInfo {

    private Long id;
    /** Not-null value. */
    private String mac;
    /** Not-null value. */
    private String ip;
    /** Not-null value. */
    private String port;
    /** Not-null value. */
    private String model;
    /** Not-null value. */
    private String version;
    private Boolean isLAN;

    public DeviceInfo() {
    }

    public DeviceInfo(Long id) {
        this.id = id;
    }

    public DeviceInfo(Long id, String mac, String ip, String port, String model, String version, Boolean isLAN) {
        this.id = id;
        this.mac = mac;
        this.ip = ip;
        this.port = port;
        this.model = model;
        this.version = version;
        this.isLAN = isLAN;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMac() {
        return mac;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /** Not-null value. */
    public String getIp() {
        return ip;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /** Not-null value. */
    public String getPort() {
        return port;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPort(String port) {
        this.port = port;
    }

    /** Not-null value. */
    public String getModel() {
        return model;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModel(String model) {
        this.model = model;
    }

    /** Not-null value. */
    public String getVersion() {
        return version;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVersion(String version) {
        this.version = version;
    }

    public Boolean getIsLAN() {
        return isLAN;
    }

    public void setIsLAN(Boolean isLAN) {
        this.isLAN = isLAN;
    }

}
