package com.eli.oneos.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.eli.oneos.db.greendao.DeviceInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DEVICE_INFO.
*/
public class DeviceInfoDao extends AbstractDao<DeviceInfo, String> {

    public static final String TABLENAME = "DEVICE_INFO";

    /**
     * Properties of entity DeviceInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Mac = new Property(0, String.class, "mac", true, "MAC");
        public final static Property Ip = new Property(1, String.class, "ip", false, "IP");
        public final static Property Port = new Property(2, String.class, "port", false, "PORT");
        public final static Property IsLAN = new Property(3, Boolean.class, "isLAN", false, "IS_LAN");
        public final static Property Time = new Property(4, Long.class, "time", false, "TIME");
    };


    public DeviceInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DeviceInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DEVICE_INFO' (" + //
                "'MAC' TEXT PRIMARY KEY NOT NULL ," + // 0: mac
                "'IP' TEXT NOT NULL ," + // 1: ip
                "'PORT' TEXT NOT NULL ," + // 2: port
                "'IS_LAN' INTEGER," + // 3: isLAN
                "'TIME' INTEGER);"); // 4: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DEVICE_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DeviceInfo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getMac());
        stmt.bindString(2, entity.getIp());
        stmt.bindString(3, entity.getPort());
 
        Boolean isLAN = entity.getIsLAN();
        if (isLAN != null) {
            stmt.bindLong(4, isLAN ? 1l: 0l);
        }
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(5, time);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DeviceInfo readEntity(Cursor cursor, int offset) {
        DeviceInfo entity = new DeviceInfo( //
            cursor.getString(offset + 0), // mac
            cursor.getString(offset + 1), // ip
            cursor.getString(offset + 2), // port
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // isLAN
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DeviceInfo entity, int offset) {
        entity.setMac(cursor.getString(offset + 0));
        entity.setIp(cursor.getString(offset + 1));
        entity.setPort(cursor.getString(offset + 2));
        entity.setIsLAN(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setTime(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(DeviceInfo entity, long rowId) {
        return entity.getMac();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(DeviceInfo entity) {
        if(entity != null) {
            return entity.getMac();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
