package com.eli.oneos.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.eli.oneos.db.greendao.DeviceHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DEVICE_HISTORY.
*/
public class DeviceHistoryDao extends AbstractDao<DeviceHistory, String> {

    public static final String TABLENAME = "DEVICE_HISTORY";

    /**
     * Properties of entity DeviceHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Ip = new Property(0, String.class, "ip", true, "IP");
        public final static Property Mac = new Property(1, String.class, "mac", false, "MAC");
        public final static Property Port = new Property(2, String.class, "port", false, "PORT");
        public final static Property Time = new Property(3, Long.class, "time", false, "TIME");
        public final static Property IsLAN = new Property(4, Boolean.class, "isLAN", false, "IS_LAN");
    };


    public DeviceHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public DeviceHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DEVICE_HISTORY' (" + //
                "'IP' TEXT PRIMARY KEY NOT NULL ," + // 0: ip
                "'MAC' TEXT NOT NULL ," + // 1: mac
                "'PORT' TEXT NOT NULL ," + // 2: port
                "'TIME' INTEGER," + // 3: time
                "'IS_LAN' INTEGER);"); // 4: isLAN
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DEVICE_HISTORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DeviceHistory entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getIp());
        stmt.bindString(2, entity.getMac());
        stmt.bindString(3, entity.getPort());
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(4, time);
        }
 
        Boolean isLAN = entity.getIsLAN();
        if (isLAN != null) {
            stmt.bindLong(5, isLAN ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DeviceHistory readEntity(Cursor cursor, int offset) {
        DeviceHistory entity = new DeviceHistory( //
            cursor.getString(offset + 0), // ip
            cursor.getString(offset + 1), // mac
            cursor.getString(offset + 2), // port
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // time
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0 // isLAN
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DeviceHistory entity, int offset) {
        entity.setIp(cursor.getString(offset + 0));
        entity.setMac(cursor.getString(offset + 1));
        entity.setPort(cursor.getString(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIsLAN(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(DeviceHistory entity, long rowId) {
        return entity.getIp();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(DeviceHistory entity) {
        if(entity != null) {
            return entity.getIp();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
