package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEVICE_HISTORY.
 */
public class DeviceHistory {

    /** Not-null value. */
    private String ip;
    /** Not-null value. */
    private String mac;
    /** Not-null value. */
    private String port;
    private Long time;
    private Boolean isLAN;

    public DeviceHistory() {
    }

    public DeviceHistory(String ip) {
        this.ip = ip;
    }

    public DeviceHistory(String ip, String mac, String port, Long time, Boolean isLAN) {
        this.ip = ip;
        this.mac = mac;
        this.port = port;
        this.time = time;
        this.isLAN = isLAN;
    }

    /** Not-null value. */
    public String getIp() {
        return ip;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /** Not-null value. */
    public String getMac() {
        return mac;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /** Not-null value. */
    public String getPort() {
        return port;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPort(String port) {
        this.port = port;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Boolean getIsLAN() {
        return isLAN;
    }

    public void setIsLAN(Boolean isLAN) {
        this.isLAN = isLAN;
    }

}
