package com.eli.oneos.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.eli.oneos.db.greendao.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table USER_INFO.
*/
public class UserInfoDao extends AbstractDao<UserInfo, String> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", true, "NAME");
        public final static Property Pwd = new Property(1, String.class, "pwd", false, "PWD");
        public final static Property Time = new Property(2, Long.class, "time", false, "TIME");
        public final static Property Uid = new Property(3, Integer.class, "uid", false, "UID");
        public final static Property Gid = new Property(4, Integer.class, "gid", false, "GID");
        public final static Property Admin = new Property(5, Integer.class, "admin", false, "ADMIN");
    };


    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'USER_INFO' (" + //
                "'NAME' TEXT PRIMARY KEY NOT NULL ," + // 0: name
                "'PWD' TEXT NOT NULL ," + // 1: pwd
                "'TIME' INTEGER," + // 2: time
                "'UID' INTEGER," + // 3: uid
                "'GID' INTEGER," + // 4: gid
                "'ADMIN' INTEGER);"); // 5: admin
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USER_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
        stmt.bindString(2, entity.getPwd());
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(3, time);
        }
 
        Integer uid = entity.getUid();
        if (uid != null) {
            stmt.bindLong(4, uid);
        }
 
        Integer gid = entity.getGid();
        if (gid != null) {
            stmt.bindLong(5, gid);
        }
 
        Integer admin = entity.getAdmin();
        if (admin != null) {
            stmt.bindLong(6, admin);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.getString(offset + 0), // name
            cursor.getString(offset + 1), // pwd
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // time
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // uid
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // gid
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // admin
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setName(cursor.getString(offset + 0));
        entity.setPwd(cursor.getString(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setUid(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setGid(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setAdmin(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(UserInfo entity, long rowId) {
        return entity.getName();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(UserInfo entity) {
        if(entity != null) {
            return entity.getName();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
