package com.eli.oneos.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.eli.oneos.db.greendao.UserHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table USER_HISTORY.
*/
public class UserHistoryDao extends AbstractDao<UserHistory, String> {

    public static final String TABLENAME = "USER_HISTORY";

    /**
     * Properties of entity UserHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", true, "NAME");
        public final static Property Pwd = new Property(1, String.class, "pwd", false, "PWD");
        public final static Property Mac = new Property(2, String.class, "mac", false, "MAC");
        public final static Property Time = new Property(3, Long.class, "time", false, "TIME");
    };


    public UserHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public UserHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'USER_HISTORY' (" + //
                "'NAME' TEXT PRIMARY KEY NOT NULL ," + // 0: name
                "'PWD' TEXT NOT NULL ," + // 1: pwd
                "'MAC' TEXT NOT NULL ," + // 2: mac
                "'TIME' INTEGER);"); // 3: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USER_HISTORY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, UserHistory entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
        stmt.bindString(2, entity.getPwd());
        stmt.bindString(3, entity.getMac());
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(4, time);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public UserHistory readEntity(Cursor cursor, int offset) {
        UserHistory entity = new UserHistory( //
            cursor.getString(offset + 0), // name
            cursor.getString(offset + 1), // pwd
            cursor.getString(offset + 2), // mac
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // time
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, UserHistory entity, int offset) {
        entity.setName(cursor.getString(offset + 0));
        entity.setPwd(cursor.getString(offset + 1));
        entity.setMac(cursor.getString(offset + 2));
        entity.setTime(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(UserHistory entity, long rowId) {
        return entity.getName();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(UserHistory entity) {
        if(entity != null) {
            return entity.getName();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
