package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_SETTINGS.
 */
public class UserSettings {

    private long uid;
    private String downloadPath;
    private Boolean isAutoBackupFile;
    private Boolean isPreviewPicOnlyWifi;
    private Boolean isTipTransferNotWifi;
    private Boolean isBackupFileOnlyWifi;
    private Long time;

    public UserSettings() {
    }

    public UserSettings(long uid) {
        this.uid = uid;
    }

    public UserSettings(long uid, String downloadPath, Boolean isAutoBackupFile, Boolean isPreviewPicOnlyWifi, Boolean isTipTransferNotWifi, Boolean isBackupFileOnlyWifi, Long time) {
        this.uid = uid;
        this.downloadPath = downloadPath;
        this.isAutoBackupFile = isAutoBackupFile;
        this.isPreviewPicOnlyWifi = isPreviewPicOnlyWifi;
        this.isTipTransferNotWifi = isTipTransferNotWifi;
        this.isBackupFileOnlyWifi = isBackupFileOnlyWifi;
        this.time = time;
    }

    public long getUid() {
        return uid;
    }

    public void setUid(long uid) {
        this.uid = uid;
    }

    public String getDownloadPath() {
        return downloadPath;
    }

    public void setDownloadPath(String downloadPath) {
        this.downloadPath = downloadPath;
    }

    public Boolean getIsAutoBackupFile() {
        return isAutoBackupFile;
    }

    public void setIsAutoBackupFile(Boolean isAutoBackupFile) {
        this.isAutoBackupFile = isAutoBackupFile;
    }

    public Boolean getIsPreviewPicOnlyWifi() {
        return isPreviewPicOnlyWifi;
    }

    public void setIsPreviewPicOnlyWifi(Boolean isPreviewPicOnlyWifi) {
        this.isPreviewPicOnlyWifi = isPreviewPicOnlyWifi;
    }

    public Boolean getIsTipTransferNotWifi() {
        return isTipTransferNotWifi;
    }

    public void setIsTipTransferNotWifi(Boolean isTipTransferNotWifi) {
        this.isTipTransferNotWifi = isTipTransferNotWifi;
    }

    public Boolean getIsBackupFileOnlyWifi() {
        return isBackupFileOnlyWifi;
    }

    public void setIsBackupFileOnlyWifi(Boolean isBackupFileOnlyWifi) {
        this.isBackupFileOnlyWifi = isBackupFileOnlyWifi;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
