package com.eli.oneos.db.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER_INFO.
 */
public class UserInfo {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String pwd;
    /** Not-null value. */
    private String mac;
    private Long time;
    private Integer uid;
    private Integer gid;
    private Integer admin;
    private String downloadPath;
    private Boolean isPreviewPicOnlyWifi;
    private Boolean isTipTransferNotWifi;
    private Boolean isAutoBackup;
    private Boolean isBackupOnlyWifi;

    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    public UserInfo(Long id, String name, String pwd, String mac, Long time, Integer uid, Integer gid, Integer admin, String downloadPath, Boolean isPreviewPicOnlyWifi, Boolean isTipTransferNotWifi, Boolean isAutoBackup, Boolean isBackupOnlyWifi) {
        this.id = id;
        this.name = name;
        this.pwd = pwd;
        this.mac = mac;
        this.time = time;
        this.uid = uid;
        this.gid = gid;
        this.admin = admin;
        this.downloadPath = downloadPath;
        this.isPreviewPicOnlyWifi = isPreviewPicOnlyWifi;
        this.isTipTransferNotWifi = isTipTransferNotWifi;
        this.isAutoBackup = isAutoBackup;
        this.isBackupOnlyWifi = isBackupOnlyWifi;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPwd() {
        return pwd;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /** Not-null value. */
    public String getMac() {
        return mac;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMac(String mac) {
        this.mac = mac;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getUid() {
        return uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public Integer getGid() {
        return gid;
    }

    public void setGid(Integer gid) {
        this.gid = gid;
    }

    public Integer getAdmin() {
        return admin;
    }

    public void setAdmin(Integer admin) {
        this.admin = admin;
    }

    public String getDownloadPath() {
        return downloadPath;
    }

    public void setDownloadPath(String downloadPath) {
        this.downloadPath = downloadPath;
    }

    public Boolean getIsPreviewPicOnlyWifi() {
        return isPreviewPicOnlyWifi;
    }

    public void setIsPreviewPicOnlyWifi(Boolean isPreviewPicOnlyWifi) {
        this.isPreviewPicOnlyWifi = isPreviewPicOnlyWifi;
    }

    public Boolean getIsTipTransferNotWifi() {
        return isTipTransferNotWifi;
    }

    public void setIsTipTransferNotWifi(Boolean isTipTransferNotWifi) {
        this.isTipTransferNotWifi = isTipTransferNotWifi;
    }

    public Boolean getIsAutoBackup() {
        return isAutoBackup;
    }

    public void setIsAutoBackup(Boolean isAutoBackup) {
        this.isAutoBackup = isAutoBackup;
    }

    public Boolean getIsBackupOnlyWifi() {
        return isBackupOnlyWifi;
    }

    public void setIsBackupOnlyWifi(Boolean isBackupOnlyWifi) {
        this.isBackupOnlyWifi = isBackupOnlyWifi;
    }

}
